import{a as L,S as v,i as l}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();async function g(e,r=1){var s,n;const a="https://pixabay.com",o="/api/",t={key:"44052553-0e6a302568f711546d3ca79ba",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await L.get(`${a}${o}`,{params:t})).data}catch(i){throw console.error(`HTTP error! status: ${((s=i.response)==null?void 0:s.status)||i.message}`),new Error(`HTTP error! status: ${((n=i.response)==null?void 0:n.status)||i.message}`)}}function w(e){return`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-item-image">
                <div class="info">
                    <p class="info-title">Likes: <span class="info-value">${e.likes}</span></p>
                    <p class="info-title">Views: <span class="info-value">${e.views}</span></p>
                    <p class="info-title">Comments: <span class="info-value">${e.comments}</span></p>
                    <p class="info-title">Downloads: <span class="info-value">${e.downloads}</span></p>
                </div>
            </a>
        </li>
    `}function h(e){return e.map(w).join("")}const b=document.querySelector(".form"),c=document.querySelector(".gallery"),u=document.querySelector("#loader"),m=document.querySelector("#load-more");let f=1,d="",p=0;const y=new v(".gallery a",{captionsData:"alt",captionDelay:250});b.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.target.elements.searchQuery.value.trim(),!d){l.error({title:"Error",message:"Search query cannot be empty!"});return}f=1,c.innerHTML="",m.classList.add("hidden"),u.classList.remove("hidden");try{const r=await g(d,f);if(p=r.totalHits,r.hits.length===0)l.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});else{const a=h(r.hits);c.innerHTML=a,y.refresh(),r.hits.length<p&&m.classList.remove("hidden"),e.target.elements.searchQuery.value=""}}catch(r){l.error({title:"Error",message:r.message})}finally{u.classList.add("hidden")}});m.addEventListener("click",async()=>{f+=1,u.classList.remove("hidden");try{const e=await g(d,f),r=h(e.hits);c.insertAdjacentHTML("beforeend",r),y.refresh(),c.querySelectorAll(".gallery-item").length>=p&&(m.classList.add("hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const o=c.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch(e){l.error({title:"Error",message:e.message})}finally{u.classList.add("hidden")}});
//# sourceMappingURL=commonHelpers.js.map
